apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.50.60-192.168.50.80
  autoAssign: true
  avoidBuggyIPs: false