apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: "v34.4.1"
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"

    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
      - "--entrypoints.web.http.middlewares=traefik-bouncer@kubernetescrd"
      - "--entrypoints.websecure.http.middlewares=traefik-bouncer@kubernetescrd"
      - "--providers.kubernetescrd"

    autoscaling:
      enabled: false

    deployment:
      enabled: true
      replicas: 4 # match with number of workers
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    metrics:
      prometheus:
        addRoutersLabels: true
        addServicesLabels: true

    nodeSelector:
      worker: "true" # add these labels to your worker nodes before running

    experimental:
      plugins:
        bouncer:
          moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: v1.4.1

    logs:
      access:
        enabled: true

    ports:
      web:
        redirections:
          entryPoint:
            priority: 10
            scheme: https
            to: websecure
      websecure:
        tls:
          enabled: true

    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec:
        loadBalancerIP: 192.168.50.65 # this should be an IP in the Kube-VIP range
        externalTrafficPolicy: Local
      loadBalancerSourceRanges: []
      externalIPs: []

    tlsStore:
      default:
        defaultCertificate:
          secretName: russellhost-tls

    volumes:
      - name: crowdsec-bouncer-tls
        mountPath: /etc/traefik/crowdsec-certs/
        type: secret
