apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crowdsec-middleware
  namespace: traefik
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: "clusters/k3s-ha/crowdsec/middleware"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system