apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  dependsOn:
    - name: reflector
  interval: 5m
  path: "clusters/k3s-ha/crowdsec/resources"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: crowdsec-lapi
      namespace: crowdsec
