apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crowdesc
  namespace: crowdesc
spec:
  dependsOn:
    - name: reflector
  interval: 5m
  path: "clusters/k3s-ha/crowdesc/resources"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: crowdsec
      namespace: crowdsec
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crowdesc-middleware
  namespace: crowdesc
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: "clusters/k3s-ha/crowdesc/middleware"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
