apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: authentik
  namespace: authentik
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: "clusters/k3s-ha/authentik/kustomize"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: authentik-server
      namespace: authentik
