apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "authentik"
  name: "authentik-redis"
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
