apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
      version: "2024.12.3"
  interval: 1m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - name: authentik-configmap
      kind: ConfigMap
      valuesKey: values.yaml
    - name: authentik-secret-values
      kind: Secret
      valuesKey: values.yaml
