apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: codeserver
  namespace: codeserver
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: "clusters/k3s-ha/codeserver/kustomize"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: code-server
      namespace: codeserver
