apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
  namespace: nextcloud
data:
  values.yaml: |
    hpa:
      enabled: false

    nextcloud:
      host: nextcloud.russellhost.org
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwritehost' => 'nextcloud.russellhost.org',
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://nextcloud.russellhost.org',
            'filelocking.enabled' => 'true',
            'loglevel' => '2',
            'enable_previews' => true,
            'trusted_domains' =>
              [
                'nextcloud',
                'nextcloud.russellhost.org'
              ]
          );

        redis.config.php: |-
          <?php
          $CONFIG = array (
            'memcache.local' => '\\OC\\Memcache\\Redis',
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => getenv('REDIS_HOST'),
              'port' => getenv('REDIS_HOST_PORT') ?: 6379,
              'password' => getenv('REDIS_HOST_PASSWORD')
            )
          );

      defaultConfigs:
        .htaccess: true
        apache-pretty-urls.config.php: true
        apcu.config.php: true
        apps.config.php: true
        autoconfig.php: false
        redis.config.php: false
        smtp.config.php: true

    persistence:
      accessMode: ReadWriteOnce
      storageClass: longhorn
      annotations: {}
      enabled: true
      size: 50Gi

    redis:
      enabled: true
      auth:
        enabled: true

    replicaCount: 1
