apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      version: "6.6.4"
  interval: 1m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - name: nextcloud-configmap
      kind: ConfigMap
      valuesKey: values.yaml
    - name: nextcloud-secret-values
      kind: Secret
      valuesKey: values.yaml
