apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  releaseName: crowdsec
  chart:
    spec:
      chart: crowdsec
      sourceRef:
        kind: HelmRepository
        name: crowdsec
      version: "0.18.0"
  interval: 1m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - name: crowdsec-configmap
      kind: ConfigMap
      valuesKey: values.yaml
    - name: crowdsec-secret-values
      kind: Secret
      valuesKey: values.yaml
