apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-code-server"
  namespace: "codeserver"
spec:
  storageClassName: "longhorn"
  volumeName: "codeserver-pv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "15Gi"