apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: codeserver
  namespace: codeserver
spec:
  releaseName: codeserver
  chart:
    spec:
      chart: ci/helm-chart
      sourceRef:
        kind: GitRepository
        name: codeserver
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 15Gi
      annotations: {}
      existingClaim: "pvc-code-server"
      # hostPath: /data
    extraArgs:
      - --auth
      - none
