apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: codeserver
  namespace: codeserver
spec:
  interval: 10m
  url: https://github.com/coder/code-server
  ref:
    branch: main
  ignore: |
    /*
    !/ci/helm-chart/