apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    configuration:
      kubernetes:
        skipTlsVerify: true
