apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 5m
  path: "clusters/k3s-ha/reflector/resources"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: reflector
      namespace: reflector
